stages:
    - install
    - test
    - deploy

variables:
    APP_ENV: testing
    CACHE_DIR: vendor/cache
    NODE_ENV: production

cache:
    key: ${CICOMMIT_REF_SLUG}
    paths:
        - vendor/
        - node_modules/

before_script:
    - php -v
    - composer --version
    - npm --version